services:
  TRAW\EventDispatch\Events\Packages\PackageEventListener:
    tags:
      - name: event.listener
        identifier: 'traw-legacy-slot'
        method: 'beforePackageActivation'
        event: TYPO3\CMS\Core\Package\Event\BeforePackageActivationEvent
      - name: event.listener
        identifier: 'traw-legacy-slot'
        method: 'afterPackageActivation'
        event: TYPO3\CMS\Core\Package\Event\AfterPackageActivationEvent
      - name: event.listener
        identifier: 'traw-legacy-slot'
        method: 'afterPackageDeactivation'
        event: TYPO3\CMS\Core\Package\Event\AfterPackageDeactivationEvent
      - name: event.listener
        identifier: 'traw-legacy-slot'
        method: 'emitAfterExtensionT3DImportSignal'
        event: TYPO3\CMS\Extensionmanager\Event\AfterExtensionDatabaseContentHasBeenImportedEvent
      - name: event.listener
        identifier: 'traw-legacy-slot'
        method: 'emitAfterExtensionStaticSqlImportSignal'
        event: TYPO3\CMS\Extensionmanager\Event\AfterExtensionStaticDatabaseContentHasBeenImportedEvent
      - name: event.listener
        identifier: 'traw-legacy-slot'
        method: 'emitAfterExtensionFileImportSignal'
        event: TYPO3\CMS\Extensionmanager\Event\AfterExtensionFilesHaveBeenImportedEvent
      - name: event.listener
        identifier: 'traw-legacy-slot'
        method: 'emitProcessActionsSignal'
        event: TYPO3\CMS\Extensionmanager\Event\AvailableActionsForExtensionEvent
      - name: event.listener
        identifier: 'traw-legacy-slot'
        method: 'packagesMayHaveChanged'
        event: TYPO3\CMS\Core\Package\Event\PackagesMayHaveChangedEvent
  TRAW\EventDispatch\Events\Backend\AfterBackendUserLoginEventListener:
    tags:
      - name: event.listener
        identifier: 'backendLogin'
        event: TRAW\EventDispatch\Events\Backend\BackendUserLoginEvent
  TRAW\EventDispatch\Events\Cache\ClearCacheEventListener:
    tags:
      - name: event.listener
        identifier: 'clearCache'
        event: TRAW\EventDispatch\Events\Cache\ClearCacheEvent
  TRAW\EventDispatch\Events\Database\DatabaseEventListener:
    tags:
      - name: event.listener
        identifer: 'traw-database'
        method: 'afterDatabaseOperation'
        event: TRAW\EventDispatch\Events\Database\AfterDatabaseOperationEvent
      - name: event.listener
        identifer: 'traw-database'
        method: 'deleteRecord'
        event: TRAW\EventDispatch\Events\Database\DeleteRecordEvent
      - name: event.listener
        identifier: 'traw-database'
        method: 'moveRecord'
        event: TRAW\EventDispatch\Events\Database\MoveRecordEvent
      - name: event.listener
        identifier: 'traw-database'
        method: 'postProcess'
        event: TRAW\EventDispatch\Events\Database\PostProcessEvent
      - name: event.listener
        identifier: 'traw-database'
        method: 'postProcessFieldArray'
        event: TRAW\EventDispatch\Events\Database\PostProcessFieldArrayEvent
      - name: event.listener
        identifier: 'traw-database'
        method: 'preProcessFieldArray'
        event: TRAW\EventDispatch\Events\Database\PreProcessFieldArrayEvent
